---
- name: NGINX server install
  hosts: web-servers
  become: yes
  vars:
    - my_name: "<h1>Soós Attila</h1>"

  tasks:

    - name: Telepítse az Nginx csomagot
      package:
        name: nginx
        state: present
      
    - name: index.html módosítása
      template:
        src: my_index.j2
        dest: /usr/share/nginx/html/index.html
      notify: Restart Nginx

      
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted